/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        // HtmlToPdfConverter htmlToPdfConverter = new HtmlToPdfConverter();
        String websiteUrl = 
        "http://info.cern.ch/hypertext/WWW/TheProject.html";
        String outputFileName = "cern";

        HtmlToPdfConverter.convert(websiteUrl, outputFileName);
    }
}
