/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        // HtmlToPdfConverter htmlToPdfConverter = new HtmlToPdfConverter();
        String websiteUrl = "https://jsoup.org/apidocs/org/jsoup/parser/XmlTreeBuilder.html#%3Cinit%3E()";
        // "https://www.google.com";
        String outputFileName = "jsoup";

        HtmlToPdfConverter.convert(websiteUrl, outputFileName);
    }
}
